fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  service:
    mailer: fos_user.mailer.twig_swift
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"
  group:
    group_class: App\Entity\Group
  registration:
    form:
      type: App\Form\RegistrationType
    confirmation:
      enabled: true