version: '3.2'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
    - app-vendor:/var/www/vendor
    - app-cache:/var/www/var/cache
    - ./:/var/www
    - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    links:
      - db:db
    environment:
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_REMOTE_PORT=9002
      - USE_UMASK=1
      - COMPOSER_PROCESS_TIMEOUT=1800
      - COMPOSER_MEMORY_LIMIT=-1


  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    links:
      - php:php
    labels:
      - "traefik.http.routers.web.rule=Host(`grouptool.localhost`)"      


  db:
    image: mysql:5.6
    volumes:
    - mysql-data/:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=symf0ny



  pma:
     image: phpmyadmin/phpmyadmin
     environment:
       - MYSQL_ROOT_PASSWORD:symf0ny
       - PMA_USER=root
       - PMA_PASSWORD=symf0ny
       - UPLOAD_LIMIT=1000M
     links:
       - db:db
     labels:
       - "traefik.http.routers.pma.rule=Host(`pma-grouptool.localhost`)"

  # rsync is needed for IDE autocompletion for the vendor directory
  rsync:
    restart: 'no'
    image: project42/rsync
    command: "-a -u --stats -h /app-vendor/ /var/www/vendor"
    volumes:
    - ./:/var/www
    - app-vendor:/app-vendor

  node:
    build: docker/node
    volumes:
      - .:/var/www
    command: bash -c "yarn && yarn encore dev --watch --watch-poll"


volumes:
  mysql-data:
  app-vendor:
  app-cache:
  node-modules:

networks:
  default:
    external:
      name: proxy