version: '3.2'

services:
  php:
    build:
      context: ./docker/php-fpm
    volumes:
    - app-vendor:/var/www/vendor
    - app-cache:/var/www/var/cache
    - node-modules:/var/www/node-modules
    - ./:/var/www:cached
    - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    - ~/.ssh:/tmp/.ssh:ro

    environment:
      - CONFIG_NAME
      - XDEBUG_REMOTE_HOST=${COMPUTERNAME}.cds-service.com
      - XDEBUG_REMOTE_PORT
      - BASE_URL_HOST
      - USE_UMASK=1
      - COMPOSER_PROCESS_TIMEOUT=900
    networks:
      - internal

  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
    - php
    - pma
    networks:
      - proxy
      - internal


  db:
    image: mysql:5.6
    volumes:
    - mysql-data/:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=symf0ny
    networks:
      - internal



  pma:
     image: nazarpc/phpmyadmin
     environment:
       - MYSQL_HOST=db;root;symf0ny
     networks:
       - internal


  # rsync is needed for IDE autocompletion for the vendor directory
  rsync:
    restart: 'no'
    image: project42/rsync
    command: "-a -u --stats -h /app-vendor/ /var/www/vendor"
    volumes:
    - ./:/var/www
    - app-vendor:/app-vendor
    depends_on:
    - php



volumes:
  mysql-data:
  app-vendor:
  app-cache:
  node-modules:

networks:
  internal:
  proxy:
    external: true
