services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false


  BirthdayBundle\Services\Menu:
    tags:
      - { name: 'grouptool.menu' , priority: 200  }


  BirthdayBundle\Services\Widget:
    tags:
      - { name: 'grouptool.widget' , priority: 200  }

  BirthdayBundle\Command\BirthdayTodayCommand:
    tags:
      - { name: 'console.command' }

  BirthdayBundle\Command\BirthdayPrewarningCommand:
    tags:
      - { name: 'console.command' }

  BirthdayBundle\BotCommands\Geburtstage:
    arguments: ['@app.telegram.bot']
    tags:
      - { name: 'telegram.botcommand' , priority: 200  }

  birthday_routes:
    class: App\Services\AddRouting
    arguments: ['BirthdayBundle/Resources/config/routing.yml']
    tags:
      - { name: 'app.addrouting' }