services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  EmailBundle\Services\TwigMailer:
    arguments: ['@mailer',  '@twig', '%mailer_from%']

  EmailBundle\Services\FosUserMailer:
    arguments: ['@EmailBundle\Services\TwigMailer',  '@router' ]

  EmailBundle\Subscriber\RegistrationSubscriber:
    arguments: ['@router.default','@EmailBundle\Services\TwigMailer' ]
    tags:
      - { name: kernel.event_subscriber}

  EmailBundle\Subscriber\UserSubscriber:
    arguments: ['@router.default','@EmailBundle\Services\TwigMailer' ]
    tags:
      - { name: kernel.event_subscriber}


  EmailBundle\Subscriber\ContactFormSubscriber:
    arguments: ['@router.default','@EmailBundle\Services\TwigMailer' ]
    tags:
      - { name: kernel.event_subscriber}

  EmailBundle\Services\ReceiverCollector: ~

  EmailBundle\Subscriber\PollSubscriber:
    arguments: ['@router.default','@EmailBundle\Services\TwigMailer','@EmailBundle\Services\ReceiverCollector' ]
    tags:
      - { name: kernel.event_subscriber}

  EmailBundle\Subscriber\EventSubscriber:
    arguments: ['@router.default','@EmailBundle\Services\TwigMailer','@EmailBundle\Services\ReceiverCollector' ]
    tags:
      - { name: kernel.event_subscriber}