services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false
    bind:
      $projectDir: '%kernel.project_dir%'

  CompanyBundle\Repository\Company: ~
  CompanyBundle\Repository\CompanyRepositoryInterface: '@CompanyBundle\Repository\Company'

  CompanyBundle\Manager\CompanyManager: ~
  CompanyBundle\Manager\CompanyManagerInterface: '@CompanyBundle\Manager\CompanyManager'

  CompanyBundle\Form\CompanyFormType: ~


  CompanyBundle\Controller\CompanyController:
    public: true
    tags: ['controller.service_arguments']

  CompanyBundle\Enums\Roles:
    tags: ['role_enum']

  company_routes:
    class: App\Services\AddRouting
    arguments: ['CompanyBundle/Resources/config/routing.yml']
    tags:
      - { name: 'app.addrouting' }